### ISSUE TITLE
Push to Docker hub

### ISSUE THREAD

**Issue by jpds** [PBWebMedia/airflow-prometheus-exporter#1]
Can someone please integrate this repo with a Docker hub account? That way we can all use the same image - I'd like to integrate this feature with the Helm chart I'm helping create for Kubernetes over at https://github.com/gsemet/kube-airflow/pull/14 .

**Comment by DemonTPx** [comment]
The image is available here: https://hub.docker.com/r/pbweb/airflow-prometheus-exporter/

**Comment by jpds** [comment]
Ah, cool - Google wasn't able to pick up the full path. :)
