### ISSUE TITLE
Environment Variable for Postgresql

### ISSUE THREAD

**Issue by theadityapathak** [PBWebMedia/airflow-prometheus-exporter#11]
when i tried to connect using my postgresql , i am getting this error:

 _export AIRFLOW_PROMETHEUS_DATABASE_HOST=postgresql+psycopg2://airflow:<pass>@3.12.104.243:5432/airflow_

2020/07/30 09:59:41 main.go:22: Starting airflow-exporter
2020/07/30 09:59:41 main.go:25: Connecting to: mysql://airflow:********@(postgresql+psycopg2://airflow:qwer1234@3.12.104.243:5432/airflow:3306)/airflow
2020/07/30 09:59:41 main.go:29: Listening on: :9112
2020/07/30 10:00:17 collector.go:110: Error while collecting data from database: default addr for network '3.12.104.243:5432/airflow:3306)' unknown
2020/07/30 10:00:28 collector.go:110: Error while collecting data from database: default addr for network '3.12.104.243:5432/airflow:3306)' unknown

**Comment by DemonTPx** [comment]
Your configuration is wrong and it should probably be something like:

```
AIRFLOW_PROMETHEUS_DATABASE_BACKEND=postgresql
AIRFLOW_PROMETHEUS_DATABASE_HOST=3.12.104.243
AIRFLOW_PROMETHEUS_DATABASE_PORT=5432
AIRFLOW_PROMETHEUS_DATABASE_USER=airflow
AIRFLOW_PROMETHEUS_DATABASE_PASSWORD=qwer1234
AIRFLOW_PROMETHEUS_DATABASE_NAME=airflow
```

**Comment by theadityapathak** [comment]
Hi @DemonTPx  ,

config should be , **export AIRFLOW_PROMETHEUS_DATABASE_BACKEND=postgres**

i tried with  , export AIRFLOW_PROMETHEUS_DATABASE_BACKEND=postgresql , but i got the error of "unknown backend postgresql".


with **postgres** , it works like charm!
