### ISSUE TITLE
Cannot use latest docker image

### ISSUE THREAD

**Issue by jacquesknipper** [PBWebMedia/airflow-prometheus-exporter#14]
Good morning,

I am trying to use the latest image but I am ending up having this issue when running it:

**standard_init_linux.go:228: exec user process caused: no such file or directory**

Anybody experiencing the same? 
Is it known?

Thanks :)

**Comment by DemonTPx** [comment]
Hi,

That's my bad. I forgot to disable CGO when building. Please pull the latest and try again.

Cheers,
Bert

**Comment by jacquesknipper** [comment]
Hey Bert,

it is actually working!

I must say I am impressed and didn't expect an answer so fast... Thanks, really! :)

Jacques
