### ISSUE TITLE
Postgres: Support optional sslmode

### ISSUE THREAD

**Issue by jparal** [PBWebMedia/airflow-prometheus-exporter#6]
Hi, I have a PostgresDB which i can connect to over SSL only.
Right now the exporter hardcodes `sslmode=disable`. Can this be optional instead?
From https://godoc.org/github.com/lib/pq
* sslmode - Whether or not to use SSL (default is require, this is not the default for libpq)
* fallback_application_name - An application_name to fall back to if one isn't provided.
* sslcert - Cert file location. The file must contain PEM encoded data.
* sslkey - Key file location. The file must contain PEM encoded data.
* sslrootcert - The location of the root certificate file. The file must contain PEM encoded data.

Valid values for sslmode are:

* disable - No SSL
* require - Always SSL (skip verification)
* verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
* verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)

**Comment by DemonTPx** [comment]
Hi, We are not using Postgres ourselves, so adding that would be a bit useless for us and would require some extra effort to test.

Could you create a PR yourself with these features? I guess the nicest way would be to get the settings from environment variables, which might also be used for the mysql connection as well...

If you are unable to make de PR, maybe @jpds would be willing to add this functionality for you? :)

**Comment by jparal** [comment]
Hi, thanks for quick response. I am not a Go developer but it looks simple enough. It will be a week or two before I get to it so if @jpds wants to give it a go I would greatly appreciate.

**Comment by DemonTPx** [comment]
I've done this.

You can use these environment variables to enable and configure postgres SSL:

    AIRFLOW_PROMETHEUS_POSTGRES_SSL_MODE=verify-full
    AIRFLOW_PROMETHEUS_POSTGRES_SSL_CERT=/path/to/certificate
    AIRFLOW_PROMETHEUS_POSTGRES_SSL_KEY=/path/to/key
    AIRFLOW_PROMETHEUS_POSTGRES_SSL_ROOT_CERT=/path/to/root_cert

**Comment by jparal** [comment]
thank you, it works like a charm.
