### ISSUE TITLE
Mask SQL password in logs

### ISSUE THREAD

**Issue by darrenhaken** [PBWebMedia/airflow-prometheus-exporter#7]
When the container starts up the connection string does not mask the password.

Can you change this?

**Comment by DemonTPx** [comment]
Hi Darren,

Thanks for creating the issue. I've changed it and it now looks like this:

    > docker run -p 9112:9112 pbweb/airflow-prometheus-exporter
    2018/07/11 07:19:58 main.go:21: Starting airflow-exporter
    2018/07/11 07:19:58 main.go:24: Connecting to: mysql://airflow:********@(localhost:3306)/airflow
    2018/07/11 07:19:58 main.go:28: Listening on: :9112

**Comment by darrenhaken** [comment]
Great that's perfect.
